# Generated by Django 2.2.1 on 2020-04-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_bus_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='buses',
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='app.Route'),
        ),
    ]
