# Generated by Django 2.2.1 on 2020-04-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200428_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_station',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_station',
        ),
    ]
