# Generated by Django 2.2.1 on 2020-04-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200428_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
