# Generated by Django 2.2.1 on 2020-04-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200428_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_id',
            field=models.CharField(max_length=255),
        ),
    ]
