# Generated by Django 2.2.1 on 2020-04-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200428_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='end_id',
            new_name='end_station',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='start_id',
            new_name='start_station',
        ),
    ]
