# Generated by Django 2.2.1 on 2020-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200428_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
