# Generated by Django 3.0.6 on 2020-05-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bus_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end_station',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_station',
            field=models.IntegerField(),
        ),
    ]
