# Generated by Django 3.0.6 on 2020-05-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200511_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='lat',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='lon',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
